### ISSUE TITLE
What is the difference between the fqkit stat and rustSKR?

### ISSUE THREAD

**Issue by MicrobioSee** [sharkLoc/fqkit#1]
Your projects look wonderful. 
What is the difference between the fqkit stat and rustSKR?

**Comment by sharkLoc** [comment]
thanks,  I'm learning the rustlang on and off, my programming style is changing, and rustSKR was born out of familiarity with the basic syntax. There are some improvements to the fqkit function, some third-party libraries are used in the project, and gzip compressed files are also supported.
